name: e2e-manual
on:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10

    env:
      APP_ENV: e2e
      NODE_ENV: test
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres?schema=public

      BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN_E2E }}
      BLOB_PREFIX: e2e

      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET_E2E }}
      NEXTAUTH_URL: http://127.0.0.1:3000

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm prisma db push
      - run: pnpm db:seed

      - run: pnpm playwright install --with-deps
      - run: pnpm e2e
